services:
  site-preview:
    container_name: site-preview-jg
    image: nginx:alpine
    labels:
      - traefik.enable=true
      - traefik.http.routers.site-preview.rule=Host(`preview.jardelguimaraes.com.br`)
      - traefik.http.routers.site-preview.entrypoints=https
      - traefik.http.routers.site-preview.tls=true
      - traefik.http.routers.site-preview.tls.certresolver=letsencrypt
      - traefik.http.services.site-preview.loadbalancer.server.port=80
    networks:
      - coolify
    ports:
      - 8091:80
    restart: unless-stopped
    volumes:
      - /opt/jg-projetos/site-jg:/usr/share/nginx/html:ro
      - /opt/jg-projetos/site-jg/preview/nginx.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  coolify:
    external: true
